#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import pickle

import numpy as np


class DataPreprocessor:
    """
    Read model data from text tables and save as binary.

    """
    def __init__(self, ic, exp, outliers=None, error=False):
        self.ic = ic
        self.exp = exp
        self.outliers = outliers
        self.error = error

    def read_table(self, name, skip_outliers=False):
        """
        Read a tabular data file, optionally skipping outlier rows.

        """
        with open('{0}/{0}_{1}.dat'.format(self.ic, name)) as f:
            if self.outliers is not None and skip_outliers:
                x = [l.split() for n, l in enumerate(f)
                     if n not in self.outliers]
            else:
                x = [l.split() for l in f]

        return np.array(x, dtype=float).squeeze()

    def save(self):
        """
        Save data to a dict of numpy arrays.

        """
        observables = ['mult', 'v2', 'v3']
        if self.error:
            observables += [obs + '_err' for obs in observables]
        data = {name: self.read_table('{}_{}'.format(name, self.exp),
                                      skip_outliers=True)
                for name in observables}
        data['design'] = self.read_table('design', skip_outliers=True)
        data['cent'] = self.read_table('cent')
        with open('{}.pkl'.format(self.ic), 'wb') as f:
            pickle.dump(data, f, pickle.HIGHEST_PROTOCOL)


def main():
    exp = 'alice'
    outliers = 0, 3

    DataPreprocessor('glb', exp, outliers=outliers).save()
    DataPreprocessor('kln', exp, outliers=outliers).save()
    DataPreprocessor('glb-validation', exp, error=True).save()


if __name__ == "__main__":
    main()
